### ISSUE TITLE
孩子你咋跑路了

### ISSUE THREAD

**Issue by jdnjk** [TPCraft/TPCraftIDACAuth#4]
咋全挂了

**Comment by LFMcxixif** [comment]
抱歉，学业繁忙，暂时没看到消息，目前已经升级为了外置登录，详情请看：[https://wiki.tpcraft.net/zh/TPCraftAPI/YggdrasilAPI](https://wiki.tpcraft.net/zh/TPCraftAPI/YggdrasilAPI)
